id: P00A41B5C
initial_creation_type: ocr
source_metadata:
  volumes:
    3b8e798e4c014b1197b84cd8116838cd:
      base_file: v067.txt
      image_group_id: I1PD95912
      title: འཕགས་པ་སཱ་ལུ་ལྗང་པ་རྒྱ་ཆེར་འགྲེལ་པ།
      total_pages: 1529
      volume_number: 67
